version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  labels: [ "dependencies", "ready for review" ]
  schedule:
    interval: "daily"
    time: "06:00"
    timezone: Europe/Amsterdam
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "06:00"
    timezone: Europe/Amsterdam
  labels: [ "dependencies", "ready for review" ]
  rebase-strategy: disabled
