# This workflow will do a clean install of node dependencies, test & lint the code and will create a
# semantic release for every merge to master.

name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install
    - run: yarn validate

  semantic_release:
    runs-on: ubuntu-latest
    needs: [tests]
    if: github.event.pull_request.merged == 'true'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Semantic release
      uses: cycjimmy/semantic-release-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
